@echo off
echo ==========================================
echo Knight Tour Game - Inno Setup Script Generator
echo ==========================================

rem Check if Inno Setup is installed (optional check, script will generate anyway)
echo Generating Inno Setup script...

set "APP_NAME=Knight Tour Game"
set "APP_VERSION=1.0.0"
set "APP_PUBLISHER=YourName"
set "APP_URL=https://github.com/your-username/knight-tour-game"
set "APP_EXE=KnightTourGame.exe"
set "SOURCE_DIR=%~dp0target\release\KnightTourGame"
set "OUTPUT_DIR=%~dp0target\installer"

if not exist "%SOURCE_DIR%" (
    echo Error: Source directory not found! Please run package_windows.bat first.
    pause
    exit /b 1
)

if not exist "%OUTPUT_DIR%" mkdir "%OUTPUT_DIR%"

(
echo ; Script generated by Knight Tour Game Build Tool
echo ; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
echo.
echo [Setup]
echo ; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
echo ; (To generate a new GUID, click Tools ^| Generate GUID inside the IDE.)
echo AppId={{C78530B6-7F3A-4F8A-9A8B-5C6D7E8F9A0B}
echo AppName=%APP_NAME%
echo AppVersion=%APP_VERSION%
echo ;AppVerName=%APP_NAME% %APP_VERSION%
echo AppPublisher=%APP_PUBLISHER%
echo AppPublisherURL=%APP_URL%
echo AppSupportURL=%APP_URL%
echo AppUpdatesURL=%APP_URL%
echo DefaultDirName={autopf}\%APP_NAME%
echo DisableProgramGroupPage=yes
echo ; Uncomment the following line to run in non administrative install mode (install for current user only.)
echo ;PrivilegesRequired=lowest
echo OutputBaseFilename=KnightTourGame_Setup_%APP_VERSION%
echo Compression=lzma
echo SolidCompression=yes
echo WizardStyle=modern
echo OutputDir=%OUTPUT_DIR%
echo.
echo [Languages]
echo Name: "english"; MessagesFile: "compiler:Default.isl"
echo Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"
echo.
echo [Tasks]
echo Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
echo.
echo [Files]
echo Source: "%SOURCE_DIR%\KnightTourGame.exe"; DestDir: "{app}"; Flags: ignoreversion
echo Source: "%SOURCE_DIR%\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
echo ; NOTE: Don't use "Flags: ignoreversion" on any shared system files
echo.
echo [Icons]
echo Name: "{autoprograms}\%APP_NAME%"; Filename: "{app}\%APP_EXE%"
echo Name: "{autodesktop}\%APP_NAME%"; Filename: "{app}\%APP_EXE%"; Tasks: desktopicon
echo.
echo [Run]
echo Filename: "{app}\%APP_EXE%"; Description: "{cm:LaunchProgram,%APP_NAME%}"; Flags: nowait postinstall skipifsilent
) > "target\installer\setup.iss"

echo Inno Setup script generated at: target\installer\setup.iss
echo.
echo To build the installer:
echo 1. Install Inno Setup (https://jrsoftware.org/isdl.php)
echo 2. Open "target\installer\setup.iss" with Inno Setup Compiler
echo 3. Click "Build" -> "Compile" (or press F9)
echo.
echo Alternatively, if you have 'iscc' in your PATH, run:
echo iscc target\installer\setup.iss
echo.
pause
